fhem/fhem-docker

- Dockerfile
added missing dependency to send emails via FHEM like described here  https://wiki.fhem.de/wiki/E-Mail_senden
> added "sendemail" package

- Dockerfile
- Dockerfile-bullseye
removed package  apt-transport-https
> removed package  apt-transport-https 

- .github/workflows/build.yml
Cleanup some variables in workflow
> Cleanup vars

- .github/workflows/build.yml
- .github/workflows/prepare-docker/action.yml
- .github/workflows/prepare-svn/action.yml
- Dockerfile
- Dockerfile-bullseye
Update master branch from dev branch
> Update master branch

- .github/workflows/build.yml
- avoid branch name in tag if building from master branch
- fix Name of fhem version
- fix SVN ref
> Update master from dev

- src/entry.sh
fix if-statement, if "find /dev/ -name \"gpio*\"" has an output
> fix entry.sh

- Dockerfile
- Dockerfile-bullseye
- Dockerfile
- Dockerfile-bullseye
> Allow newer npm packages as 5.8

- .github/workflows/build.yml
- .github/workflows/prepare-docker/action.yml
- use gha cache
- update actions in composite file
> some build improvements

- Dockerfile
- Dockerfile-bullseye
added Protocol::WebSocket
- bullseye via APT
- buster via CPAN
> Better support for fhempy 

- Dockerfile
- Dockerfile-bullseye
Try to fix broken Nodejs 14 / npm  since Version 3.2.3
Implemented build targets for base and with-fhem stage.
> build[nodejs]: Updated install method for Node 16

- src/entry.sh
- src/tests/bats/entry.bats
- Fixes that a logfile definition is patched to the correct filename with placeholders.
> Logfile definition patched with real Logfile

- .github/workflows/build.yml
Latest tag not for threaded or prereleases
> Prevent latest tag not for threaded or prereleases

- .github/workflows/build.yml
- Dockerfile-bullseye
- Dockerfile-threaded-bullseye
- src/entry.sh
- src/tests/bats/aptInstall.bats
- src/tests/bats/entry.bats
- src/tests/bats/health-check.bats
- src/tests/bats/logfile.bats
- src/tests/bats/network.bats
- src/tests/bats/pidfile.bats
- src/tests/bats/setup_suite.bash
- added tests
- added missing iproute2 pkg
- tests for net type host added
> fix auto detect DOCKER_GW and setting of DOCKER_HOST

- .github/workflows/build.yml
- Dockerfile-bullseye
- Dockerfile-threaded-bullseye
> fix[Dockerfile]: Device:Serialport and imagesize

- Dockerfile-bullseye
- Dockerfile-threaded-bullseye
fix[Dockerfile] Inline-python ist missing since Beta 8 Fixes #199
> Add python-dev to allow inline-python to be build via cpm / cpanm

- .github/workflows/build.yml
- Dockerfile-bullseye
- Dockerfile-threaded-bullseye
- scripts/excluded_packages.txt
- scripts/get-FHEMRepositorys.sh
- scripts/parse-METAJson.pl
- use filter also for META search
- Improved filter generation with a text file
- do not require core Modules
- do not scan contrib or archived repos
> Remove  requirements, which are provided with FHEM or FHEM Modules

- Dockerfile-bullseye
- Dockerfile-threaded-bullseye
> Do not install lib nmap parser perl package via apt

- src/entry.sh
- src/tests/bats/network.bats
If network mode is hostmode the variable is checks to prevent a crash
> Fix unbound Variable DOCKER_GW 

- .github/workflows/build.yml
- Dockerfile-bullseye
- Dockerfile-threaded-bullseye
- scripts/excluded_packages.txt
- build tools removed
- dev libs removed
- binarys from cpan builds removed
> Use slim variant for running image

- Dockerfile-bullseye
graphviz was missing to install AI:Decisiontree from cpan
> fix AI:Decisiontree

- README.md
- src/entry.sh
- src/tests/bats/entry.bats
Added logmessage
added tests
added note to README
> Add logmessage if fhem revision is to old for DockerImageInfo Module

- .github/workflows/build.yml
- .github/workflows/prepare-docker/action.yml
- Dockerfile-bullseye
- Dockerfile-threaded-bullseye
- scripts/excluded_packages.txt
> Provide perl package GD
